skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
yield_vault = "5DTpb6picURvKtEVjXWbdX9coNFERr1gWDS8f59YXmMk"

[programs.devnet]
yield_vault = "5DTpb6picURvKtEVjXWbdX9coNFERr1gWDS8f59YXmMk"

[provider]
cluster = "localnet"
wallet = ".keys/deployer.json"

[scripts]
test = "cargo test"

[hooks]
